### ISSUE TITLE
setup.py can't find progressbar

### ISSUE THREAD

**Issue by apmechev** [revoltek/losoto#15] opened 2017-01-09 10:54 UTC
Installing with python setup.py install cannot find progressbar, even though it's in the losoto folder.

`Installed /home/softdrive.nl/lofar_sw/losoto/current/lib/python2.7/site-packages/losoto-0.5-py2.7.egg
Processing dependencies for losoto==0.5
Searching for progressbar
Reading https://pypi.python.org/simple/progressbar/
Download error on https://pypi.python.org/simple/progressbar/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'progressbar' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or download links found for progressbar
error: Could not find suitable distribution for Requirement.parse('progressbar')
`

The progressbar folder is in losoto/ when it's pulled from the github however
`$ ls losoto/
h5parm.py  importer.py  __init__.py  __init__.pyc  _logging.py  operations  operations_lib.py  progressbar  _version.py  _version.pyc
`

**Comment by nudomarinero** [comment] 2017-01-09 12:07
I could not reproduce the problem.

If pip cannot find progressbar it is likely to raise this error. It looks like a problem with the secure connections in your Python system. The key is "unknown url type: https". If you have compiled Python manually it probably could not find the development SSL libraries whilst compiling (libssl-dev or openssl-devel depending on the system) and does not support https connections.

One possible workarround is to force pip to use http. You can try to install progressbar with:
```
pip install --index-url=http://pypi.python.org/simple/ --trusted-host progressbar
```

**Comment by apmechev** [comment] 2017-01-10 13:42
Hi
the machine I am installing on doesn't have pip. I suppose the only option is a manual wget;untar;export $PATHs;install ?

**Comment by revoltek** [comment] 2017-01-10 13:44
But progressbar should be shipped with losoto, it's inside the losoto directory indeed... this would be the easiest thing of all, just pass it as a module provided by us

**Comment by nudomarinero** [comment] 2017-01-10 13:57
@apmechev Then you can just edit the setup.py and remove progressbar from the "install_requires".
```
install_requires=['numpy','cython','numexpr>=2.0','tables>=3.0']
```
You do not need to manually install progressbar because it is already bundled with losoto. Just tell the install script to no to bother trying to install it.

Actually, if you are manually managing the dependencies you can leave the array empty. It will not fail if you have installed the dependencies manually.

By the way, you could also install pip with "python get-pip.py" using the script at https://bootstrap.pypa.io/get-pip.py as explained in https://pip.pypa.io/en/stable/installing/

**Comment by nudomarinero** [comment] 2017-01-23 17:35
I think we can close this by now.

**Closed** 2017-01-23 17:35 UTC
