### ISSUE TITLE
issue with bandpass -- amp_xx and freq lengths do not match

### ISSUE THREAD

**Issue by lmorabit** [revoltek/losoto#59] opened 2018-07-24 07:45 UTC
I'm trying to run essentially what is the prefactor calibrator parset, and it's failing on the following step:

[bandpass]
soltab               =   [.*/amplitude000]
operation            =   PREFACTOR_BANDPASS
chanWidth            =   97khz

with the following error:

Traceback (most recent call last):
  File "/home/lmorabit/losoto/bin/losoto", line 144, in <module>
    returncode += ops[ op ]._run_parser( soltab, parser, step )
  File "/home/lmorabit/losoto/losoto/operations/prefactor_bandpass.py", line 22, in _run_parser
    autoFlag, nSigma, maxFlaggedFraction, maxStddev, ncpu)
  File "/home/lmorabit/losoto/losoto/operations/prefactor_bandpass.py", line 528, in run
    assert len(amp_xx_tmp[:]) == len(freq_tmp[:])
AssertionError

It seems that len(amp_xx_tmp[:]) is 23 -- the number of antennas;  while len(freq_tmp[:]) is 262 -- the number of channels.

Any suggestions for what might be going wrong?

**Comment by adrabent** [comment] 2018-07-24 12:20
Hi Leah,

could you provide your h5parm file, so that I can try to reproduce this error?

Cheers,
Alex

**Comment by lmorabit** [comment] 2018-07-26 15:12
It's on CEP3 here:

/data020/scratch/lmorabit/test_delay_cal/delay_calib_noRS.h5

Please note @revoltek that this isn't *actually* a prefactor parset run, I've simply done a diagonal solve using NDPPP and am trying to run a losoto parset using the new version of losoto on the result -- which I couldn't find anywhere except in the prefactor pipeline.

**Comment by adrabent** [comment] 2018-07-27 13:07
Please let me know if this fixes your issue

**Comment by lmorabit** [comment] 2018-07-27 14:16
That does not fix my issue.  Were you able to reproduce the error?

**Comment by adrabent** [comment] 2018-07-27 15:04
Yes, I could reproduce the error.
Have you downloaded this version of losoto:
https://github.com/adrabent/losoto/tree/patch-6

since the changes have not yet been merged with the master branch.

**Comment by lmorabit** [comment] 2018-07-27 15:09
Ah, no, I'll try that in a minute.

**Comment by lmorabit** [comment] 2018-07-29 16:55
Just to be sure -- I should have the patch if I do:

`git checkout -b patch-6 `

right?  That means I'm still getting the same error. :(

**Comment by adrabent** [comment] 2018-07-30 07:31
Hmm.. I don't know whether this works.
But you could try this:

```
git clone https://github.com/adrabent/losoto.git
cd losoto
git checkout patch-6
```

**Closed** 2018-08-01 14:40 UTC

**Comment by lmorabit** [comment] 2018-08-01 15:56
Hi Francesco, could you please not close this issue until it is actually resolved?

**Comment by revoltek** [comment] 2018-08-01 18:11
I authorized the commit of alexander that was tagged as a solution of this issue, github automatically closed it

**Comment by lmorabit** [comment] 2018-08-01 23:16
Okay.  I'll test it again tomorrow, but it hasn't solved my issue yet ...

**Comment by lmorabit** [comment] 2018-08-02 09:20
@adrabent that's fixed the issue, but now it's failing on the next step, PREFACTOR_XYOFFSET with the following error:

INFO: --> Starting 'xyoffset' step (operation: PREFACTOR_XYOFFSET).
INFO: Running XYoffset on: phase000
Traceback (most recent call last):
  File "/home/lmorabit/software/losoto/bin/losoto", line 144, in <module>
    returncode += ops[ op ]._run_parser( soltab, parser, step )
  File "/home/lmorabit/software/losoto/losoto/operations/prefactor_XYoffset.py", line 12, in _run_parser
    return run(soltab, chanWidth)
  File "/home/lmorabit/software/losoto/losoto/operations/prefactor_XYoffset.py", line 83, in run
    refphases = phases_tmp[:, refstationID, :, :]
IndexError: index 2 is out of bounds for axis 1 with size 1
Closing remaining open files:
delay_calib_noRS.h5...


Perhaps it would be better to test the entire losoto parset I'm using?

h5parm: /data/scratch/lmorabit/test_delay_cal/delay_calib_noRS.h5 
(a copy exists too, copy_delay_calib_noRS.h5)
test parset: /data/scratch/lmorabit/test_delay_cal/test_losoto.parset
real parset I want to run: /data/scratch/lmorabit/test_delay_cal/losoto_master2.parset

The real parset made it through the clock/TEC as the first steps but this took forever so that's why I made a test parset.

**Comment by adrabent** [comment] 2018-08-02 09:44
I also had to reorder the axes for the XYoffset task. It should work now.

**Comment by lmorabit** [comment] 2018-08-02 11:03
great, it works for me now!  thanks.
