### ISSUE TITLE
REWEIGHT flags entire soltab

### ISSUE THREAD

**Issue by tikk3r** [revoltek/losoto#62] opened 2018-08-09 12:00 UTC
While testing the prefactor 3.0 pipeline, the `REWEIGHT` step in `prepare_losoto_PA` flags everything for the `rotation000` table. We confirmed it by running just this step on a single instrument table, from a single sub-band. Changing `flagBad` on `True` or `False` has no effect, aside from unflagging flagged stations when set to turned off.

**Test parset**
```
ncpu = 10

[flag]
operation=REWEIGHT
flagBad=True
soltab=sol000/rotation000

[plot]
operation=PLOT
soltab=sol000/rotation000
axesInPlot=time
axisInTable=ant
plotFlag=True
prefix=rotangle_reweight
refant=CS001HBA0
minmax=[-3.1,3.1]
```

**Single sub-band**
![rotation_plot](https://user-images.githubusercontent.com/2464769/43897265-c2ab45fe-9bdb-11e8-9bc1-17df3523a8f8.png)

**After test parset**
![rotation_plot_reweight](https://user-images.githubusercontent.com/2464769/43897266-c2c32124-9bdb-11e8-98fc-85cb68bb824d.png)

**Comment by tikk3r** [comment] 2018-08-09 12:29
The `fr.png` (except the for reference antenna) and `fr_rotangle.png` plots are empty as well. They are preceded by a REWEIGHT as well, so I'm assuming it's the same issue. The other plots do not seem to have the flagging issue.

**Comment by revoltek** [comment] 2018-08-09 13:08
Losoto should run in the proper way: you told it to flag "bad values" which are ==0 for all tables apart from ==1 for amplitudes. This is a DPPP convention. However, now DPPP automatically reference rotations to station 0 which is therefore ==0 everywhere. As a consequence losoto flags it during that step. Furthermore, you are referencing your plots in the plot step to the same (now fully flagged) antenna. Therefore all other values end up impossible to plot (note that they are NOT flagged). This should NOT appear if you remove that step (which indeed it was there for the time where DPPP didn't handle flags, now it does) or if you set flagBad==False. If the problem is there with the flagBad == False, then it is a bug and I'd like to have the h5parm.

fra

**Comment by rvweeren** [comment] 2018-08-09 13:30
Ah, so the problem is in prefactor then, where it runs with flagBad=True (and thus flags the reference station....).

**Comment by rvweeren** [comment] 2018-08-09 13:48
In the new prefactor parsets pushed today this issue seems to have been addressed. Issue can be closed by someone with the right permissions.

**Comment by revoltek** [comment] 2018-08-10 12:31
Yes the problem was the leftover of that operation from some testing

**Closed by revoltek** 2018-08-10 12:31 UTC
